name: Assign PR Reviewer

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  assign-reviewer:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewer
        run: |
          if [ ${{ github.event.pull_request.user.login }} = "BrunoMendes27" ]; then
            REVIEWER="RafaelFaria98"
          else
            REVIEWER="BrunoMendes27"
          fi

          gh api \
            repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            --method POST \
            --input <(echo "{\"reviewers\":[\"$REVIEWER\"]}")
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
